[package]
name = "bunnystorage-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
chrono = "0.4.40"
reqwest = "0.12.12"
serde = { version = "1.0.218", features = ["derive"]}
serde_json = "1.0.139"

[dev-dependencies]
tokio = { version = "1.43.0", features = ["full"] }
